version: 2
jobs:
  build:
    docker:
      - image: php
    steps:
      - checkout
  test1:
    docker:
      - image: php
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libgmp3-dev
      - run: apt-get install php-pear -y
      - run: pear channel-update pear.php.net
      - run: pear upgrade pear
      - run: pear config-set auto_discover 1
      - run: apt-get install phpunit -y
      - run: phpunit sampleTest
workflows:
  version: 2
  build_and_test:
    jobs:
      - test1